run:
  timeout: 5m
  issues-exit-code: 2
  tests: false
  skip-dirs:
    - tmp/
    - dist/
    - vendor/
  skip-files:
    # Temporarily ignore the file which uses libgit2 dependency since this will 
    # fail on the static check.
    - manifest/pack_pull_git.go

linters:
  disable-all: true
  enable:
    - govet
    - misspell
    - staticcheck
