name: Build environment

# Build only on changes to the build environment itself
on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  archs:
    strategy:
      matrix:
        include:
          - GCC_ARCH: x86_64
            GCC_VERSION: 12.2.0
          # - GCC_ARCH: arm
          #   GCC_VERSION: 12.2.0
          # - GCC_ARCH: arm64
          #   GCC_VERSION: 12.2.0
    runs-on: ubuntu-latest
    env:
      GCC_SUFFIX:

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: ./buildenvs/gcc.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/gcc:${{ matrix.GCC_VERSION }}-${{ matrix.GCC_ARCH }}${{ env.GCC_SUFFIX }}
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        env:
          UK_ARCH: ${{ matrix.GCC_ARCH }}

  qemu:
    runs-on: ubuntu-latest
    env:
      QEMU_VERSION: 7.1.0

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        uses: docker/build-push-action@v3
        with:
          file: ./buildenvs/qemu.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/qemu:${{ QEMU_VERSION }}
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}

  myself:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./buildenvs/myself.Dockerfile
          tags: index.unikraft.io/kraftkit.sh/myself:latest
          platforms: linux/amd64
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
  
  base:
    runs-on: ubuntu-latest
    needs: [archs, qemu, myself]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REG_USER }}
          password: ${{ secrets.REG_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: index.unikraft.io/kraftkit.sh/base:latest
